version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.8-alpine
    ports:
      # The standard AMQP protocol port
      - '5672:5672'
  web:
    build: .
    depends_on:
      - rabbitmq
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    #: .venv/bin/coverage run manage.py test OnToology;  .venv/bin/coverage report


