version: '3'


services:
  stiqueue:
    image: ahmad88me/stiqueue:latest
    ports:
      # The standard AMQP protocol port
      - '1234:1234'
  web:
    build: .
    depends_on:
      - stiqueue
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    #: .venv/bin/coverage run manage.py test OnToology;  .venv/bin/coverage report


