version: '3'

services:
  db:
    image: mongo:4.0.9-xenial
    ports:
      - "27017:27017"
  web:
#    environment:
#    - db_host=db
#    - db_port=27017
#    - github_password
#    - client_id_login
#    - client_id_public
#    - client_id_private
#    - client_secret_login
#    - client_secret_public
#    - client_secret_private
#    - test_user_token
#    - test_user_email
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    #: .venv/bin/coverage run manage.py test OnToology;  .venv/bin/coverage report


